### ISSUE TITLE
[Epic] Log viewing

### ISSUE THREAD

**Issue by manuranga** [wso2/integration-control-plane#1]
Viewing logs, especially system out aka wso2cabon.log and wire logs, are the primary tools used to find and troubleshoot issues.

- [ ] Create Log API - API to get wso2carbon.log for MI, system out for Ballerina.
- [ ] Chunked Log API - Log index API that partitions the logs by time, allowing caching of logs.
- [ ] Log frontend - Show log timeline and logs
- [ ] Log filtering
