### ISSUE TITLE
[Epic] Monitor view

### ISSUE THREAD

**Issue by manuranga** [wso2/integration-control-plane#5]
Display an at-a-glance view of the deployment's status.

- [] [Ext/MI] Improve MI heartbeat to send node statistics
- [] [Ext/Bal] Improve Ballerina heartbeat to send node statistics
- [] Improve ICP in-memory heartbeat store to keep time series data
- [] Persist ICP heartbeat store
- [] [Ext/MI] New API to get deployment summary
- [] [Ext/Bal] New API to get deployment summary
